version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    image: yolo-frontend:latest
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      front-end-network:
        ipv4_address: 172.127.0.3
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "5050:5050"
    environment:
      MONGODB_URI: 'mongodb://mourice:mourice@172.128.0.3:27017'
      PORT: 5050
    depends_on:
      - mongodb
    networks:
      front-end-network:
        ipv4_address: 172.127.0.2
      backend-end-network:
        ipv4_address: 172.128.0.2
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mourice
      MONGO_INITDB_ROOT_PASSWORD: mourice
    networks:
      backend-end-network:
        ipv4_address: 172.128.0.3

networks:
  front-end-network:
    ipam:
      driver: default
      config:
        - subnet: 172.127.0.0/16
  backend-end-network:
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
