version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    image: yolo-frontend:latest
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      front-end-network:
        ipv4_address: 172.127.0.3
